# SNAKEMAKE FILE FOR SOMETALP METAGENOMIC PROJECT
# Last Updated: 2025-11-19
# Author: Matias Becker Burgos (Matias.BeckerBurgos@unil.ch)

##################################################
# DESCRIPTION
##################################################
# Main Pipeline file to Launch the SOMETALP Metagenomic project
# The file is modifiable per module if some steps need to be added or removed
# Steps  incuded:
# 01: Concatenation and preprocessing
# 02: Metagenome Assembly
# 03: Binning
# 04: Annotation
# 05: Reporting

##################################################
# CONFIGURATION
##################################################
configfile: "../config/config.yaml"

##################################################
# SET UP VARIABLES
##################################################

## Directory Variables
# Raw Data directory variable
DATA_DIR = config["input_dir"]

# Scratch directory variable
SCRATCH_DIR = config["scratch_dir"]

# Output (Working) directory variable
OUTPUT_DIR = config["working_dir"]

# Log directory variable
LOG_DIR = config["log_dir"]

# Benchmark directory variable
BENCH_DIR = config["benchmark_dir"]

## Other Variables
# Add other variables as needed
include: "rules/00_common.smk"
SAMPLES = detect_samples(DATA_DIR) # Function to detect samples from the data directory
print(f"Detected samples: {SAMPLES}")

##################################################
# RULE ALL
##################################################

rule all:
    input:
        #f"{OUTPUT_DIR}/02_Results/01_QC_Preprocessing/HF/HF_refstats.tsv"
        f"{OUTPUT_DIR}/02_Results/01_QC_Preprocessing/Kraken2/Combined_kraken2_report.tsv"
        #f"{OUTPUT_DIR}/02_Results/01_QC_Preprocessing/QC_After" # After_mutliQC results directory
        #expand(f"{OUTPUT_DIR}/01_Analysis/01_QC_Preprocessing/QC_Before/{{sample}}_R{{read}}_concat_fastqc.html", sample=SAMPLES, read=["1", "2"]),
        #expand(f"{OUTPUT_DIR}/01_Analysis/01_QC_Preprocessing/QC_Before/{{sample}}_R{{read}}_concat_fastqc.zip", sample=SAMPLES, read=["1", "2"])
    
        #expand(f"{SCRATCH_DIR}/Concatenated/{{sample}}_R1_concat.fastq.gz", sample=SAMPLES),
        #expand(f"{SCRATCH_DIR}/Concatenated/{{sample}}_R2_concat.fastq.gz", sample=SAMPLES)
        # Add other final output files as needed
   
##################################################
# RULES
##################################################
# Include individual rule files for modularity

include: "rules/01_quality_control_preprocessing.smk"
#include: "rules/02_assembly.smk"
#include: "rules/03_binning.smk"
#include: "rules/04_annotation.smk"
#include: "rules/05_reporting.smk"

# Add additional rules as needed

##################################################
# END OF SNAKEMAKE FILE
##################################################