# CONFIGURATION FILE FOR SOMETALP METAGENOMIC PROJECT
# Last Updated: 2025-11-10
# Author: Matias Becker Burgos (Matias.BeckerBurgos@unil.ch)

######################################################
# DESCRIPTION
######################################################
# This configuration file contains paths and parameters for the SOMETALP
# metagenomic analysis pipeline. Adjust the paths below to match your
# project structure and computational environment.
######################################################
# WORKING DIRECTORIES
######################################################
# directory where all the analysis will be performed.
# Examples:
#   working_dir: /home/username/projects/2025_SOMETALP_MetaG_Project

working_dir: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/mbeckerb/2025_SOMETALP_MetaG_Project

# path to a scratch directory for temporary files.
# Examples:
#   scratch_dir: /tmp/username

scratch_dir: /scratch/mbeckerb

# path to the raw data directory containing input FASTQ files.

input_dir: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/mbeckerb/2025_SOMETALP_MetaG_Project/00_Data/01_Raw_Data

# path to the log directory for storing log files.

log_dir: /users/mbeckerb/Projects/2025_SOMETALP_MetaG_Project/logs

#########################################################
# REFERENCE DATABASES
#########################################################


