# CONFIGURATION FILE FOR SOMETALP METAGENOMIC PROJECT
# Last Updated: 2025-12-18
# Author: Matias Becker Burgos (Matias.BeckerBurgos@unil.ch)

######################################################
# DESCRIPTION
######################################################
# This configuration file contains paths and parameters for the SOMETALP
# metagenomic analysis pipeline. Adjust the paths below to match your
# project structure and computational environment.
######################################################
# WORKING DIRECTORIES
######################################################
# directory where all the analysis will be performed.
# Examples:
#   working_dir: /home/username/projects/2025_SOMETALP_MetaG_Project

working_dir: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/mbeckerb/2025_SOMETALP_MetaG_Project

# path to a scratch directory for temporary files.
# Examples:
#   scratch_dir: /tmp/username

scratch_dir: /scratch/mbeckerb

# path to the raw data directory containing input FASTQ files.

input_dir: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/mbeckerb/2025_SOMETALP_MetaG_Project/00_Data/02_Clean_Data

# path to the log directory for storing log files.

log_dir: /users/mbeckerb/Projects/2025_SOMETALP_MetaG_Project/logs

# path to the benchmark directory for storing benchmark files.
benchmark_dir: /users/mbeckerb/Projects/2025_SOMETALP_MetaG_Project/benchmark

#########################################################
# INCLUDE/EXCLUDE STEPS
#########################################################
# Set to true or false to include/exclude specific steps
steps:
  taxonomic_profiling: true  # Include taxonomic profiling step
  alternative_binning: false  # Include alternative binning with MetaBAT2
  MAGs_Reporting_step: true # Include MAGs reporting step
  Instrain_analysis: true # Include InStrain analysis step
  Co_diversification_analysis: true # Include Co-diversification analysis step

#########################################################
# SOFTWARE PARAMETERS
#########################################################
# General parameters for all tools

######## 01 Preprocessing.smk parameters ########

# Concatenate parameters
Concatenate:
  threads: 2
  runtime_min: 5

# FastQC parameters
fastqc:
  threads: 2
  memory_mb: 1000
  runtime_min: 35

# MultiQC parameters
multiqc:
  threads: 1
  memory_mb: 600
  runtime_min: 10

# Trimmomatic parameters
trimmomatic:
  trimmomatic_adapters: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/trimmomatic/adapters/NexteraPE-PE.fa
  leading: 28
  trailing: 28
  minlen: 60
  # Ressources allocation
  threads: 8
  memory_mb: 6000
  runtime_min: 300

# Kraken2 parameters (host filtering + taxonomic classification rules)
# Database parameters
kraken2_db:
  DB_dir: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/kraken2_db
  # Ressources allocation for building the database
  threads: 32
  memory_mb: 500000
  runtime_min: 2880
  disk_mb: 1000000
# Formatted Reference genomes for host filtering in Kraken2
  refseq:
  - /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Apodemus_sylvaticus/GCF_947179515.1_mApoSyl1.1_genomic_kraken.fna # Apodemus_sylvaticus
  - /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Chionomys_nivalis/GCF_950005125.1_mChiNiv1.1_genomic_kraken.fna # Chionomys_nivalis
  - /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Arvicola_amphibius/GCF_903992535.2_mArvAmp1.2_genomic_kraken.fna # Arvicola_amphibius
  - /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Microtus_arvalis/GCA_044665705.1_MicArv1.0_genomic_kraken.fna # Microtus_arvalis
  - /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Myodes_glareolus/GCF_902806735.1_Bank_vole1_10x_genomic_kraken.fna # Myodes_glareolus
  - /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Sorex_araneus/GCF_027595985.1_mSorAra2.pri_genomic_kraken.fna # Sorex_araneus
    

# Run parameters
kraken2_run:
  threads: 4
  memory_mb: 200000
  runtime_min: 180


# Bowtie2 parameters for host filtering 
# Index building parameters
host_indexing:
  threads: 20
  memory_mb: 50000
  runtime_min: 240
  # Reference genomes for host filtering in Bowtie2
  Host_refs:
  - "/work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Apodemus_sylvaticus/GCF_947179515.1_mApoSyl1.1_genomic.fna" # Apodemus_sylvaticus
  - "/work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Chionomys_nivalis/GCF_950005125.1_mChiNiv1.1_genomic.fna" # Chionomys_nivalis
  - "/work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Arvicola_amphibius/GCF_903992535.2_mArvAmp1.2_genomic.fna" # Arvicola_amphibius
  - "/work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Microtus_arvalis/GCA_044665705.1_MicArv1.0_genomic.fna" # Microtus_arvalis
  - "/work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Myodes_glareolus/GCF_902806735.1_Bank_vole1_10x_genomic.fna" # Myodes_glareolus
  - "/work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Sorex_araneus/GCF_027595985.1_mSorAra2.pri_genomic.fna" # Sorex_araneus
  - "/work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/Host_Database/Homo_sapiens/GCF_000001405.40_GRCh38.p14_genomic.fna" # Homo_sapiens

# Host filtering parameters
host_filtering:
  # Ressources allocation
  threads: 20
  memory_mb: 30000
  runtime_min: 600
  # Index for host filtering
  index_path: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/bowtie2_index/SOMETALP_index 

########## 02 Assembly.smk parameters ########

# Metaspade parameters
Metaspade_assembly:
  threads: 10
  memory_mb: 350000
  runtime_min: 2880


# MetaQuast parameters
MetaQuast:
  threads: 4
  memory_mb: 64000
  runtime_min: 120


# Contig filtering parameters
Contig_filter:
  length_threshold: 1500 # this is a default of 1kb
  coverage_threshold: 1

########### 03 Binning.smk parameters #############
# SAMPLE excluded from the Binning
exclude_samples:
- Pl1_H3
- Pl1_H6

########### Backmapping ###################
# Bowtie2 parameters
Contig_indexing:
  threads: 8
  memory_mb: 16000
  runtime_min: 120

Contig_Backmapping:
  threads: 16
  memory_mb: 40000
  runtime_min: 4320

######### Binning Tools Parameters #########
# Metabat2 parameters

MetaBat2:
  threads: 8
  memory_mb: 15000
  runtime_min: 300
  # extra options
  min_contig_length: 1500 # default 2500 bp for Metabat2

# Maxbin2 parameters
MaxBin2:
  threads: 16
  memory_mb: 30000
  runtime_min: 2880
  # extra options
  min_contig_length: 1500 # default 1000 bp for Maxbin2

# CONCOCT parameters
CONCOCT:
  threads: 8
  memory_mb: 15000
  runtime_min: 2880
  # extra options
  min_contig_length: 1500 # default 1000 bp for CONCOCT
  chunk_size: 10000 # default 10000 bp for CONCOCT
  overlap_size: 0 # default 2500 bp for CONCOCT
  coverage_runtime: 120

# DASTool parameters
DASTool:
  threads: 8
  memory_mb: 64000
  runtime_min: 120
  # extra options
  search_engine: diamond # default is usearch, can be set to diamond


############ QC parameters #############

# CheckM parameters
CheckM:
  threads: 4
  memory_mb: 128000
  runtime_min: 240
  # set CheckM database path if needed
  db: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/shared/Database/checkM_db

# Bin quality filtering parameters
Bin_filtering:
  completeness: 90
  contamination: 5

############ 04 MAGs parameters #############

# GTDB-Tk parameters
GTDB_Tk:
  threads: 32
  memory_mb: 64000
  runtime_min: 1440
  # set GTDB-Tk database path if needed
  db: /work/FAC/FBM/DMF/pengel/general_data/common_databases/gtdb/release226 # GTDB-Tk database path (temporary borrowed from engel lab)

# DATA VARIABLES AND COLORS FOR ITOL VISUALIZATIONS
DATA_VARIABLES:
  metadata_path: /work/FAC/FBM/DBC/fmazel/gut_evol_stg/mbeckerb/2025_SOMETALP_MetaG_Project/00_Data/00_Metadata/Metadata_SOMETALP_MetaG_2022_FMazel_Geo.xlsx # Path to metadata file
  col_host: "Species_ID_final" # Column name in metadata file for host species
  split_criteria: "_DASTool_" # Character to split user_genome to extract Sample_ID
  col_sample_id: "Fastq_Sample_ID" # Column name in metadata file for sample IDs

# Colors for host species in iTOL visualizations
host_colors:
  Sorex_araneus: "#8da9c4"
  Sorex_coronatus: "#13315c"
  Apodemus_flavicollis: "#99582a"
  Apodemus_sylvaticus: "#432818"
  Apodemus_alpicola: "#ffe6a7"
  Microtus_lavernedii: "#386641"
  Myodes_glareolus: "#6a994e"
  Arvicola_amphibius: "#a7c957"
  Chionomys_nivalis: "#f2e8cf"


# dRep parameters
dRep:
  threads: 16
  memory_mb: 64000
  runtime_min: 1440
  # extra options
  completeness_threshold: 90 # default 50% for dRep
  contamination_threshold: 5 # default 10% for dRep
  secondary_clustering_ANI: 0.95 # default 95% for dRep secondary clustering

############ 05a_Instrain_Analysis.smk parameters #############
# Bowtie2 parameters for InStrain analysis
SGBs_indexing:
  threads: 8
  memory_mb: 16000
  runtime_min: 120

SGBs_mapping:
  threads: 16
  memory_mb: 40000
  runtime_min: 4320

# InStrain parameters
InStrain:
  threads: 8
  memory_mb: 250000
  runtime_min: 1440


############### 05b_Co-diversification.smk parameters #############
# Iqtree parameters for phylogenetic tree construction
Phylo_iqtree:
  threads: 16
  memory_mb: 64000
  runtime_min: 4320

# Co-diversification analysis parameters
Co_diversification:
  threads: 4
  memory_mb: 16000
  runtime_min: 120

